/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./components/layout/AppLayout.vue')['default']
    CommandBar: typeof import('./components/layout/CommandBar.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Header: typeof import('./components/layout/Header.vue')['default']
    MainContent: typeof import('./components/mqtt/MainContent.vue')['default']
    MessageList: typeof import('./components/mqtt/MessageList.vue')['default']
    MessagePayload: typeof import('./components/mqtt/MessagePayload.vue')['default']
    PublishPanel: typeof import('./components/mqtt/PublishPanel.vue')['default']
    QuickSendPanel: typeof import('./components/template/QuickSendPanel.vue')['default']
    ScheduledPublishDialog: typeof import('./components/mqtt/ScheduledPublishDialog.vue')['default']
    ScriptDialog: typeof import('./components/script/ScriptDialog.vue')['default']
    ServerFormDialog: typeof import('./components/mqtt/ServerFormDialog.vue')['default']
    ServerInfoBar: typeof import('./components/mqtt/ServerInfoBar.vue')['default']
    SettingsDialog: typeof import('./components/settings/SettingsDialog.vue')['default']
    Sidebar: typeof import('./components/layout/Sidebar.vue')['default']
    TemplateDialog: typeof import('./components/template/TemplateDialog.vue')['default']
    TemplateDrawer: typeof import('./components/template/TemplateDrawer.vue')['default']
    TemplateList: typeof import('./components/template/TemplateList.vue')['default']
    TemplateManager: typeof import('./components/template/TemplateManager.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
